### ISSUE TITLE
How is this different from Marathon?

### ISSUE THREAD

**Issue by hfossli** [yonaskolb/Mint#10]
Is it similar? How is it different? :)

**Comment by yonaskolb** [comment]
Hi @hfossli
They are similar, though Marathon was designed to run swift files as scripts and Mint is designed to run existing command line tools.

Having said that, I’ve just learned from John that Marathon recently added the ability to also run command line tools, though that isn’t in a tagged release yet.

The other thing Mint has that Marathon doesn’t yet is the ability to run specific versions.

**Comment by hfossli** [comment]
Awesome. I find versioning really important. 

Can you tell me a bit more about the first part (scripts vs cli tools)?

**Comment by yonaskolb** [comment]
In this particular case a script would be a single file that would be run. A Swift command line tool (CLI - Command Line Interface) is a full Swift PM package that includes an `executable` target. In the package you can have multiple targets and frameworks all contributing to your final executable. These later ones is what Mint can build and install.

If you have any other questions let me know.
