### ISSUE TITLE
Failed to build Ice. Use --verbose to see full output

### ISSUE THREAD

**Issue by PlaceRem** [yonaskolb/Mint#101]
Hello. I am trying to install Ice (https://github.com/jakeheis/Ice) and get error.

`🌱  Finding latest version of Ice
🌱  Resolved latest version of Ice to 0.7.0
🌱  Cloning https://github.com/jakeheis/Ice.git 0.7.0...
🌱  Building Ice Package with SPM...
Failed to build Ice. Use --verbose to see full output`

When I go to manual mode. As saying below:

git clone https://github.com/jakeheis/Ice
cd Ice
swift build -c release
mv .build/release/ice /usr/bin/local/ice

I got next error:
`error: cannot load underlying module for 'XCTest'
import XCTest
       ^
error: terminated(1): /Library/Developer/CommandLineTools/usr/bin/swift-build-tool -f /Users/Admin/Ice/.build/release.yaml main output:`

How to avoid error and install Ice?

**Comment by yonaskolb** [comment]
Hi @PlaceRem. What version of Swift do you have?
```
swift --version
```

**Comment by PlaceRem** [comment]
@yonaskolb, Swift version 4.1.2.

**Comment by yonaskolb** [comment]
On macOS or Linux?

**Comment by PlaceRem** [comment]
macOS

**Comment by yonaskolb** [comment]
Looks like this was solved here https://github.com/jakeheis/Ice/issues/25
