### ISSUE TITLE
Unable to link framework

### ISSUE THREAD

**Issue by wangqingzhouleo** [yonaskolb/Mint#108]
* Using Mint version 0.11.2

When installing dependencies with `mint bootstrap`, I was not able to build the dependency if the framework is already installed via Carthage.
To solve this issue, I need to specify the name `mint install carthage/carthage --verbose` and type `y` in the final step:
```
🌱  An executable that was not installed by mint already exists at /usr/local/bin/carthage that is symlinked to /usr/local/Cellar/carthage/0.31.1/bin/carthage.
Ovewrite it with Mint's symlink? (y/n)
```

Can we add something like `mint bootstrap --overwrite` to force over write everything?

**Comment by yonaskolb** [comment]
Bootstrap doesn’t actually link versions globally at all. It’s designed for setting up the dependencies to run locally with `mint run`

Or are you actually getting an error of some sort?

**Comment by yonaskolb** [comment]
Well if you can provide the error that you get (perhaps by reinstalling Carthage with brew or something and then trying again) then we can see what the issue is

**Comment by wangqingzhouleo** [comment]
Hmm it's not happening anymore.
I will set up everything from scratch later, and let you know if there's any issue.
