### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by wangqingzhouleo** [yonaskolb/Mint#109]
https://github.com/yonaskolb/Mint/blob/155c44d3b9edca1433dd1c8e380b4f1d098e3fac/Sources/MintKit/Mint.swift#L394

Found a typo at this line. `Ovewrite`

**Comment by yonaskolb** [comment]
Good catch @wangqingzhouleo! Could you open a PR? Github makes it easy to do these types of changes by just hitting `edit` on the file. It will automatically create a fork, branch and PR for you. It makes it just as easy as opening an issue like this 😄

**Comment by yonaskolb** [comment]
Closed by #110
