### ISSUE TITLE
`mint run swiftformat` seems like it requires itself as an executable parameter

### ISSUE THREAD

**Issue by awe-mt** [yonaskolb/Mint#112]
When running `swiftformat` with a path I get the following output:

```
> mint run swiftformat path/
🌱  Using nicklockwood/SwiftFormat 0.35.8 from Mintfile.
🌱  SwiftFormat 0.35.8 already installed
Couldn't find executable "path/"
```

When running just `swiftformat` I get the following output:

```
> mint run swiftformat
🌱  Using nicklockwood/SwiftFormat 0.35.8 from Mintfile.
🌱  SwiftFormat 0.35.8 already installed
🌱  Running swiftFormat 0.35.8...

swiftformat, version 0.35.8
copyright (c) 2016 Nick Lockwood

--help             print this help page
...
```

For some reason, it works by running `mint run swiftformat swiftformat path/`

I don't have that issue with swiftlint. I would rather install locally, rather than globally. However, just to test more possibilities, I went ahead and installed it globally, and `swiftformat path/` worked fine. Any ideas? Should this issue be filed at `nicklockwood/swiftformat` instead?

**Comment by yonaskolb** [comment]
Hi @awe-mt. Yes if you pass arguments using Mint you need to specify the executable name as well 
https://github.com/yonaskolb/Mint/issues/111

**Comment by awe-mt** [comment]
Understood! Thank you, and sorry for the duplicate issue.

**Comment by yonaskolb** [comment]
No problem 😀👍

**Comment by tapi** [comment]
Is there a reason for this behaviour? Seems counter intuitive compared to tools like bundler where exec just forwards the rest of the arguments to the command invoked by exec

**Comment by guillaumealgis** [comment]
I agree with @tapi, this is super counter intuitive and definitely look like a bug.

This looks awkward :

```
mint run swiftformat swiftformat --config .swiftformat --lint --verbose .
```

This looks natural :

```
mint run swiftformat --config .swiftformat --lint --verbose .
```

I'm strongly in favor of re-opening this issue and changing this behavior, or at the **very** least documenting it in the README.

**Comment by yonaskolb** [comment]
@guillaumealgis `swift run` is run from within a package directory so the package is know. Mint has to do a lookup for the repo/package first.
I've left a comment here addressing this https://github.com/yonaskolb/Mint/issues/145 which is another issues that tracks this
