### ISSUE TITLE
Update via `install` does not work for branches

### ISSUE THREAD

**Issue by Jeehut** [yonaskolb/Mint#123]
Note sure if this is a duplicate of #12 but when I install a fork of a tool for testing a new feature, I run something like this:

```bash
mint install Dschee/periphery@fail-on-warnings
```

Then I test the new features and have to update my branch if I find any issues. But when I run the same command again to update to the newest commit, I get this:

```bash
🌱  periphery fail-on-warnings already installed
🌱  Linked periphery fail-on-warnings to /usr/local/bin
```

So it's not updating although the latest commit of the branch changed on the GitHub repo. I would expect Mint to check if the local branch is up-to-date before stating that it's already intalled.

My `mint version`:

``` bash
Version: 0.11.3
```

**Comment by yonaskolb** [comment]
Yeah at the moment we don't check the SHA's of installs, and don't calculate if a `@version` is a branch.
To workaround this use `--force`

```
mint install Dschee/periphery@fail-on-warnings --force
```
