### ISSUE TITLE
Enchance bootstrap command with Mintfile creation

### ISSUE THREAD

**Issue by cbounta** [yonaskolb/Mint#126]
As part of maintaining my dotfiles, I usually find it nice to have a list of all of my installed software versions etc of my system, and because i recently started using Mint, i thought i could enhance the mint bootstrap command with that functionality.

For that reason, in my local fork of Mint I have added to the bootstrap command a --dump parameter that leads to the creation of a Mintfile based on the packages and the versions currently installed.

eg.

mint bootstrap --dump 

the command fails if a Mintfile is already present, and it's not going to overwrite it till you add also the force param

mint bootstrap --dump --force

Would this be something interesting for Mint? If yes, I have some questions, before making a PR :)

**Comment by yonaskolb** [comment]
I can see the use in this. Perhaps this could be a new command like `mint dump`. Please feel free to open a PR. What were the questions you had?

**Comment by ChrisBountalis** [comment]
Alright then, you can considder this issue in progress, I will make a pr soon.

Well in my first question you kinda answered already. I was going to ask if you would prefer a separate command. So I will refactor my existing code to "mint dump".

My second question has to do with the way of getting the repo owner. I followed similar logic that is currently used for the packageName, but  don't really like the components.count -2, so I was wondering whether there is an other way to get this information:

` let components = packagePath.lastComponent.split(separator: "_")
  let repoOwner = String(components[components.count - 2])
  let packageName = String(components.last!)`
