### ISSUE TITLE
`mint run --silent` isn't totally silent when no version is specified in the Mintfile

### ISSUE THREAD

**Issue by guillaumealgis** [yonaskolb/Mint#142]
Example Mintfile:

```
realm/SwiftLint
```

```bash
❯ mint run --silent swiftlint swiftlint
🌱  MINTFILE: repository realm/SwiftLint has no defined version. Specify a version using <Repo>@<Commitish>.
Loading configuration from '.swiftlint.yml'
Linting Swift files at paths 
Linting 'Foobar.swift' (1/1)
Done linting! Found 0 violations, 0 serious in 1 files.
```

With the `--silent` option, I expected the lines 

> 🌱  MINTFILE: repository foobar/Foobar has no defined version. Specify a version using <Repo\>@<Commitish\>.

to not appear on stdout.

**Comment by guillaumealgis** [comment]
Ok so after digging a bit more, it seems the message appears because it is not printed on stdout but on stderr.

So multiple solutions from here I thinks:

- Consider that having no version specified in the Mintfile is not actually an error (one might want to always use the latest version of a package), and print the message on stdout instead of stderr;
- Redirect both stdout **and** stderr to /dev/null when using the `--silent` flag. Potentially dangerous, but it would be a somewhat logical behavior given the name of the flag;
- Keep things as-is.

**Comment by yonaskolb** [comment]
Hi @guillaumealgis, I've gone ahead and removed the warning entirely on master

**Comment by guillaumealgis** [comment]
Great, thank you @yonaskolb !
