### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by SDGGiesbrecht** [yonaskolb/Mint#15]
It would be nice if Mint would run on Linux too.

(If this is already the case, it would be nice if the read‐me states as much and **it would be wise to have CI run its tests on Linux.**)

**Comment by mcandre** [comment]
For now, Mint fails to compile in Ubuntu 16.04:

```console
$ sudo apt-get update
$ sudo apt-get install -y make git
$ git clone https://github.com/yonaskolb/Mint.git
$ sh -c 'cd Mint && make && sudo make install'
...
error: use of unresolved identifier 'CFAbsoluteTimeGetCurrent'
```

**Comment by yonaskolb** [comment]
Linux support in progress in #82
