### ISSUE TITLE
How do I min run an installed package offline?

### ISSUE THREAD

**Issue by el-hoshino** [yonaskolb/Mint#164]
Hi

I need some help, that I installed some packages via a Mintfile with `$ mint bootstrap`, and I'd like to run them with `$ mint run package`, but `mint run` will hit a latest version checking process that if I'm offline, I can't run my package.

I know that I can bootstrap the Mintfile with `$ mint bootstrap -l` and then I can run `$ package` directly from the terminal, but obviously I lose the package version management in the project, so I'd prefer `$ mint run package` over `$package`

So is there a way to run `$ mint run package` offline?

Thanks

**Comment by vknabel** [comment]
Hi @el-hoshino!

If you *explicitly* provide an already installed version, it will still continue to work offline.
This is valid for the CLI param (`$ mint run user/package@1.0.0`) and the Mintfile.

```
user/package@1.0.0
```


---

Nonetheless, I created a PR https://github.com/yonaskolb/Mint/pull/166 which will try to find local versions when not specified.

**Comment by el-hoshino** [comment]
Hi @vknabel 

Thanks for the PR! It seems very helpful to me ❤️
