### ISSUE TITLE
Get Executable Name(s) etc. from Package Manifest

### ISSUE THREAD

**Issue by SDGGiesbrecht** [yonaskolb/Mint#17]
The `swift package` command can retrieve a lot of information from the package manifest, so that Mint does not have to guess.

(This is especially significant on case‐sensitive file systems #14, where Mint currently guesses its own name wrong.)

**Comment by SDGGiesbrecht** [comment]
Some related notes have been discussed in #12.

**Comment by yonaskolb** [comment]
I'm thinking of implementing it like this:

The executable name will read from `Package.swift`. Some packages contain multiple executables however, so a new `--executable` argument will be added. (this deprecates the old `name` parameter on install)

**Install**
Install all executables locally, and globally. If you pass an `--executable` argument, only that executable is installed.

**Run**
If there is a single executable, run that. If there are multiple, output that you need to pass an explicit `--executable` (or perhaps prompt for the executable with the addition of a `--no-interactive` flag to suppress this)

**MintFile**
Add a way of specifying an executable for a package if there are multiple of them. That way only that one will be installed and run

**Comment by SDGGiesbrecht** [comment]
I have not thought about this for a while and now I cannot remember why I requested it in the first place. Maybe it was somehow related to one of the issues linked in earlier comments? 🤷‍♂️

In any case my interim solution ([`curl` + Gist](https://gist.github.com/SDGGiesbrecht/4d76ad2f2b9c7bf9072ca1da9815d7e2)) requires it to be explicit anyway, and at this point I would probably continue being explicit even if I can one day switch to Mint.

@yonaskolb, if *you* think it would be useful you can implement it, but you are also free to just close this issue as no longer relevant. I leave it up to you.

**Comment by yonaskolb** [comment]
Yeah, I think it's a useful enhancement. Was just noting my potential solution down here for myself, but also for you and others to see
