### ISSUE TITLE
Stop Keeping Tool Repositories Around

### ISSUE THREAD

**Issue by SDGGiesbrecht** [yonaskolb/Mint#18]
It is dangerous to keep a tool repositories around for reuse.

It is not just about saving space (though that is reason enough in and of itself).

In the event of a force push, even to an unrelated branch, several Git commands will suddenly begin to fail.

When a new version of Swift comes out and `swift build` creates new files (such as Swift 4 did with `Package.resolved`), it causes the repository to become dirty and causes problems with future attempts to check something out.

For reasons such as this it would be safer to clone, build, copy the product(s) and then remove the repository each time. (The products themselves are safe to cache for future use.)

**Comment by yonaskolb** [comment]
This would also resolve #12 in a brute force way. 
What we would lose out on is the download time each time you update, but I guess Swift PM projects aren't usually that big so it's not a huge issue

**Comment by yonaskolb** [comment]
One question to consider now though is what happens when `mint run` is called without a specific version. Because we don't have the repo cached we can't get the latest tag, which means the whole repo will have to be downloaded again.

We either leave it like this, or assume "master" which make the behaviour different from run and install/update

**Comment by yonaskolb** [comment]
I think I'm just going to leave it as it is and document that leaving the version out will require a git clone

**Comment by SDGGiesbrecht** [comment]
@yonaskolb, you can get the version list from `git ls‐remote --tags` without recloning the whole repository.

(All you have to do is sort the versions.)

**Comment by SDGGiesbrecht** [comment]
See [here](https://github.com/SDGGiesbrecht/SDGCommandLine/blob/ef7246f10c71bcbb2465ddc51b7561aa014860bd/Sources/SDGCommandLine/External%20Tools/Git.swift#L99) for a full implementation if you want to use `git ls-remote`.
