### ISSUE TITLE
Couldn't pass any arguments to executables

### ISSUE THREAD

**Issue by giginet** [yonaskolb/Mint#20]
I supported Mint for my CLI.

However, Mint can't recognize any arguments for executables.

In the situation which `mycommand` provides help command:

```console
$ swift run mycommand help
...
```

```console
$ mint run mycommand help
🌱  Using latest tag "1.0.0"
🌱  Checking out https://github.com/giginet/mycommand.git "1.0.0"...
🌱  Building help. This may take a few minutes...
🌱  Installing help...
🌱  Error: Couldn't find command help
```

**Comment by yonaskolb** [comment]
Hi @giginet 
If you pass any commands or arguments you need to pass the full command in quotes
Try this: 
```
swift run giginet/mycommand "mycommand help"
```

**Comment by giginet** [comment]
It works! 
It is already said in README :flushed:
Thanks.
