### ISSUE TITLE
Self hosted Mint install fails

### ISSUE THREAD

**Issue by davidweiss** [yonaskolb/Mint#203]
% git clone https://github.com/yonaskolb/Mint.git

Cloning into 'Mint'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 1952 (delta 10), reused 17 (delta 6), pack-reused 1916
Receiving objects: 100% (1952/1952), 357.89 KiB | 2.03 MiB/s, done.
Resolving deltas: 100% (1113/1113), done.

% cd Mint
% swift run mint install yonaskolb/mint

Fetching https://github.com/mxcl/Version.git
Fetching https://github.com/jakeheis/SwiftCLI.git
Fetching https://github.com/onevcat/Rainbow.git
Fetching https://github.com/kylef/PathKit.git
Fetching https://github.com/kylef/Spectre.git
Cloning https://github.com/jakeheis/SwiftCLI.git
Resolving https://github.com/jakeheis/SwiftCLI.git at 6.0.1
Cloning https://github.com/kylef/PathKit.git
Resolving https://github.com/kylef/PathKit.git at 1.0.0
Cloning https://github.com/onevcat/Rainbow.git
Resolving https://github.com/onevcat/Rainbow.git at 3.1.5
Cloning https://github.com/mxcl/Version.git
Resolving https://github.com/mxcl/Version.git at 1.1.2
Cloning https://github.com/kylef/Spectre.git
Resolving https://github.com/kylef/Spectre.git at 0.9.0
[70/70] Linking mint
🌱 Finding latest version of mint
🌱 Cloning mint 0.16.0
🌱 Resolving package
🌱 Building package
Error: You don’t have permission to save the file “0.16.0” in the folder “build”.

% swift run mint install yonaskolb/mint

🌱 Finding latest version of mint
🌱 Cloning mint 0.16.0
🌱 Resolving package
🌱 Building package
Error: You don’t have permission to save the file “0.16.0” in the folder “build”.

**Comment by davidweiss** [comment]
This was on macOS Big Sur Version 11.2.1 with Xcode Version 12.4 (12D4e)

**Comment by davidweiss** [comment]
% make

swift build --disable-sandbox -c release --arch arm64 --arch x86_64
0%: CreateBuildDirectory /Users/davidweiss/Code/Mint/.build/apple/Products
0%: CreateBuildDirectory /Users/davidweiss/Code/Mint/.build/apple/Intermediates.noindex
0%: Write Version.modulemap
0%: Write SwiftCLI.modulemap
0%: Write Version.o.SwiftFileList (x86_64)
0%: Write Version-OutputFileMap.json (x86_64)
0%: Write Version.o.SwiftFileList (arm64)
0%: Write Version.o.LinkFileList (x86_64)
0%: Write Version-OutputFileMap.json (arm64)
0%: Write Version.o.LinkFileList (arm64)
0%: Write Rainbow.modulemap
0%: Write SwiftCLI.o.LinkFileList (arm64)
0%: Write SwiftCLI.o.SwiftFileList (arm64)
0%: Write SwiftCLI-OutputFileMap.json (arm64)
0%: Write SwiftCLI.o.LinkFileList (x86_64)
0%: Write SwiftCLI.o.SwiftFileList (x86_64)
0%: Write SwiftCLI-OutputFileMap.json (x86_64)
0%: Write Rainbow.o.SwiftFileList (x86_64)
0%: Write Rainbow.o.LinkFileList (x86_64)
0%: Copy Version.modulemap
0%: Copy SwiftCLI.modulemap
0%: Write Rainbow-OutputFileMap.json (x86_64)
0%: Compile Swift source files (x86_64)
0%: Write Rainbow.o.SwiftFileList (arm64)
0%: Write Rainbow.o.LinkFileList (arm64)
0%: Write Rainbow-OutputFileMap.json (arm64)
0%: Compile Swift source files (arm64)
0%: Write PathKit.modulemap
0%: Copy Rainbow.modulemap
0%: Write PathKit.o.SwiftFileList (x86_64)
0%: Write PathKit.o.LinkFileList (x86_64)
0%: Compile Swift source files (arm64)
0%: Write PathKit-OutputFileMap.json (x86_64)
0%: Compile Swift source files (x86_64)
0%: Write PathKit.o.SwiftFileList (arm64)
0%: Write PathKit.o.LinkFileList (arm64)
0%: Write PathKit-OutputFileMap.json (arm64)
0%: Compile Swift source files (x86_64)
0%: Compile Swift source files (arm64)
0%: Copy PathKit.modulemap
0%: Compile Swift source files (x86_64)
0%: Compile Swift source files (arm64)
0%: Compile Swift source files (arm64)
0%: Compile Swift source files (x86_64)
0%: Compile Swift source files (arm64)
0%: Compile Swift source files (x86_64)
0%: Compile PathKit.swift (x86_64)
0%: Compile Swift source files (arm64)
0%: Compile Swift source files (x86_64)
0%: Compile PathKit.swift (arm64)
23%: Copy Rainbow.swiftmodule (arm64)
23%: Copy Rainbow.swiftmodule (arm64)
23%: Copy Rainbow.swiftdoc (arm64)
23%: Copy Rainbow.swiftdoc (arm64)
23%: Copy Rainbow.swiftsourceinfo (arm64)
23%: Copy Rainbow.swiftsourceinfo (arm64)
23%: Copy Version.swiftdoc (arm64)
23%: Copy Version.swiftdoc (arm64)
23%: Copy Version.swiftmodule (arm64)
23%: Copy Version.swiftmodule (arm64)
23%: Copy Version.swiftsourceinfo (arm64)
23%: Copy Version.swiftsourceinfo (arm64)
23%: Copy PathKit.swiftdoc (arm64)
23%: Copy PathKit.swiftmodule (arm64)
23%: Copy PathKit.swiftdoc (arm64)
23%: Copy PathKit.swiftmodule (arm64)
23%: Copy PathKit.swiftsourceinfo (arm64)
23%: Copy PathKit.swiftsourceinfo (arm64)
23%: Copy Rainbow.swiftmodule (x86_64)
23%: Copy Rainbow.swiftmodule (x86_64)
23%: Processing…
23%: Copy Rainbow.swiftdoc (x86_64)
23%: Copy Rainbow.swiftsourceinfo (x86_64)
23%: Copy Rainbow.swiftsourceinfo (x86_64)
23%: Copy Rainbow.swiftdoc (x86_64)
23%: Copy Version.swiftmodule (x86_64)
23%: Copy Version.swiftdoc (x86_64)
23%: Processing…
23%: Copy Version.swiftmodule (x86_64)
23%: Copy Version.swiftdoc (x86_64)
23%: Copy Version.swiftsourceinfo (x86_64)
23%: Copy Version.swiftsourceinfo (x86_64)
23%: Copy PathKit.swiftmodule (x86_64)
23%: Processing…
23%: Copy PathKit.swiftdoc (x86_64)
23%: Copy PathKit.swiftmodule (x86_64)
23%: Copy PathKit.swiftdoc (x86_64)
23%: Copy PathKit.swiftsourceinfo (x86_64)
23%: Copy PathKit.swiftsourceinfo (x86_64)
23%: Link Rainbow.o (arm64)
23%: Link Rainbow.o (x86_64)
23%: Link Version.o (x86_64)
23%: Link Version.o (arm64)
23%: Link PathKit.o (arm64)
23%: Link PathKit.o (x86_64)
47%: Copy SwiftCLI.swiftmodule (arm64)
47%: Copy SwiftCLI.swiftdoc (arm64)
47%: Copy SwiftCLI.swiftsourceinfo (arm64)
47%: Copy SwiftCLI.swiftmodule (arm64)
47%: Copy SwiftCLI.swiftsourceinfo (arm64)
47%: Copy SwiftCLI.swiftdoc (arm64)
50%: Processing…
50%: Copy SwiftCLI.swiftsourceinfo (x86_64)
50%: Copy SwiftCLI.swiftdoc (x86_64)
50%: Copy SwiftCLI.swiftsourceinfo (x86_64)
50%: Copy SwiftCLI.swiftdoc (x86_64)
50%: Copy SwiftCLI.swiftmodule (x86_64)
50%: Copy SwiftCLI.swiftmodule (x86_64)
50%: Link SwiftCLI.o (x86_64)
50%: Link SwiftCLI.o (arm64)
50%: Write MintKit.modulemap
50%: Write MintKit.o.SwiftFileList (arm64)
50%: Write MintKit-OutputFileMap.json (arm64)
50%: Write MintKit.o.SwiftFileList (x86_64)
50%: Write MintKit-OutputFileMap.json (x86_64)
50%: Copy MintKit.modulemap
50%: Compile Swift source files (arm64)
50%: Compile Swift source files (x86_64)
50%: Compile Swift source files (arm64)
50%: Compile Swift source files (x86_64)
59%: Create universal binary Version.o
59%: Create universal binary PathKit.o
59%: Create universal binary Rainbow.o
59%: Register execution policy exception for Version.o
59%: Register execution policy exception for Rainbow.o
59%: Register execution policy exception for PathKit.o
59%: Create universal binary SwiftCLI.o
59%: Register execution policy exception for SwiftCLI.o
59%: Write MintKit.o.LinkFileList (x86_64)
59%: Write MintKit.o.LinkFileList (arm64)
65%: Copy MintKit.swiftmodule (arm64)
65%: Copy MintKit.swiftdoc (arm64)
65%: Copy MintKit.swiftmodule (arm64)
65%: Copy MintKit.swiftdoc (arm64)
65%: Copy MintKit.swiftsourceinfo (arm64)
65%: Copy MintKit.swiftsourceinfo (arm64)
68%: Processing…
68%: Copy MintKit.swiftmodule (x86_64)
68%: Copy MintKit.swiftsourceinfo (x86_64)
68%: Copy MintKit.swiftdoc (x86_64)
68%: Copy MintKit.swiftdoc (x86_64)
68%: Copy MintKit.swiftmodule (x86_64)
68%: Copy MintKit.swiftsourceinfo (x86_64)
68%: Link MintKit.o (arm64)
68%: Link MintKit.o (x86_64)
68%: Write MintCLI.modulemap
68%: Write MintCLI.o.SwiftFileList (x86_64)
68%: Write MintCLI-OutputFileMap.json (x86_64)
68%: Write MintCLI-OutputFileMap.json (arm64)
68%: Write MintCLI.o.SwiftFileList (arm64)
68%: Copy MintCLI.modulemap
68%: Compile Swift source files (x86_64)
68%: Compile Swift source files (arm64)
68%: Compile Swift source files (x86_64)
68%: Create universal binary MintKit.o
68%: Compile Swift source files (arm64)
68%: Register execution policy exception for MintKit.o
68%: Write MintCLI.o.LinkFileList (x86_64)
68%: Write MintCLI.o.LinkFileList (arm64)
78%: Copy MintCLI.swiftmodule (arm64)
78%: Copy MintCLI.swiftdoc (arm64)
78%: Copy MintCLI.swiftdoc (arm64)
78%: Copy MintCLI.swiftmodule (arm64)
78%: Copy MintCLI.swiftsourceinfo (arm64)
78%: Copy MintCLI.swiftsourceinfo (arm64)
78%: Processing…
78%: Copy MintCLI.swiftdoc (x86_64)
78%: Copy MintCLI.swiftmodule (x86_64)
78%: Copy MintCLI.swiftmodule (x86_64)
78%: Copy MintCLI.swiftdoc (x86_64)
78%: Copy MintCLI.swiftsourceinfo (x86_64)
78%: Copy MintCLI.swiftsourceinfo (x86_64)
78%: Link MintCLI.o (x86_64)
78%: Link MintCLI.o (arm64)
78%: Write mint-OutputFileMap.json (arm64)
78%: Write mint.SwiftFileList (arm64)
78%: Write mint-OutputFileMap.json (x86_64)
78%: Write mint.SwiftFileList (x86_64)
78%: Compile Swift source files (arm64)
78%: Compile Swift source files (x86_64)
78%: Create universal binary MintCLI.o
78%: Compile main.swift (x86_64)
78%: Compile main.swift (arm64)
78%: Register execution policy exception for MintCLI.o
78%: Write mint.LinkFileList (x86_64)
78%: Write mint.LinkFileList (arm64)
91%: Link mint (arm64)
91%: Link mint (x86_64)
91%: Copy Mint.swiftdoc (x86_64)
91%: Copy Mint.swiftdoc (arm64)
91%: Copy Mint.swiftmodule (arm64)
91%: Copy Mint.swiftmodule (x86_64)
91%: Copy Mint.swiftdoc (x86_64)
91%: Copy Mint.swiftmodule (x86_64)
91%: Copy Mint.swiftmodule (arm64)
91%: Copy Mint.swiftdoc (arm64)
91%: Copy Mint.swiftsourceinfo (x86_64)
91%: Copy Mint.swiftsourceinfo (x86_64)
91%: Copy Mint.swiftsourceinfo (arm64)
91%: Copy Mint.swiftsourceinfo (arm64)
98%: Create universal binary mint
98%: Generate mint.dSYM
98%: Register execution policy exception for mint
100%: Build succeeded
mkdir -p /usr/local/bin
cp -f .build/apple/Products/Release/mint /usr/local/bin/mint
cp: /usr/local/bin/mint: Permission denied
make: *** [install] Error 1

**Comment by danramteke** [comment]
I'm running into the same issue. Have you found a workaround @davidweiss ?

I have set `MINT_LOAD_PATH` to a local directory as well as workaround (mentioned in https://github.com/yonaskolb/Mint/issues/188#issuecomment-799655593), but unfortunately that did not help.

**Comment by davidweiss** [comment]
I haven't found a workaround.

**Comment by yonaskolb** [comment]
Thanks @davidweiss, see here for the same issue and some workarounds https://github.com/yonaskolb/Mint/issues/188
