### ISSUE TITLE
Using Mint in mac M1 chip

### ISSUE THREAD

**Issue by NghiemDv10** [yonaskolb/Mint#215]
i am using mac m1 bigsur 11.5.2
I can't use mint to install libraries
it gives the following error: 
![Screen Shot 2021-09-12 at 14 16 26](https://user-images.githubusercontent.com/88356823/132977414-29bcde12-9527-41da-a909-fa3842f11547.png)
Please help me

**Comment by yonaskolb** [comment]
Fixed by https://github.com/yonaskolb/Mint/pull/216
