### ISSUE TITLE
Add no-install option to run

### ISSUE THREAD

**Issue by yonaskolb** [yonaskolb/Mint#22]
Add an option to not install when executing `run`

**Comment by toshi0383** [comment]
Just wondering: what's specific use case for this?

**Comment by yonaskolb** [comment]
Maybe someone has something running on an automated system that would prefer to have this run quickly and throw an error if not installed instead of installing slowly. It's not a huge feature

**Comment by Lutzifer** [comment]
> Maybe someone has something running on an automated system that would prefer to have this run quickly and throw an error if not installed instead of installing slowly. It's not a huge feature

I actually would prefer this over installing all the mint dependencies during an Xcode build script phase.
If it is not installed, the dev has simply not run the preparation shell script (something we call bootstrap.sh) beforehand.

**Comment by LinusU** [comment]
I personally love that it installs it if it's not present, and would very much like to see that stay as the default.

The problem that I have seen with `bootstrap.sh` is that it's hard to keep them up-to-date unless you have a steady influx of new developers. As soon as you have a period without team growth, the file will usually go stale.

Mint beautifully works around this by not having a "setup" step, and I think it's one of the main selling points of Mint 🌱

**Comment by Lutzifer** [comment]
// Its getting a bit offtopic

@LinusU we keep the bootstrap.sh up to date by having it updatable with a `-u` flag and having it publicly available under https://github.com/num42/n42-buildscripts/blob/master/bootstrap.sh

It's shared across web and iOS projects and can be specified by adding a file name bootstrap-specialised.sh in the project. Works great so far over 10 projects.

**Comment by ivasilev-pe** [comment]
From the documentation:

> run: Runs a package. This will install it first **if it isn't already installed**, though won't link it globally. It's useful for running a certain version.

Is this issue is still in Open status?

**Comment by ivasilev-pe** [comment]
@yonaskolb hello! Could you please take a look at my comment above, whenever you have time? We're trying to use Mint on a production project, but encountering issues each time when packages versioned by Mint are getting an update... Maybe we're doing something wrong in regards to install / bootstrap  / run though

**Comment by yonaskolb** [comment]
@ivasilev-pe I'm not sure what your issue is. Are you saying after you `mint bootstrap` that when you `mint run` it is still `Finding latest version` instead of using the version from the Mintfile? Can you post your Mintfile?
