### ISSUE TITLE
Error: encountered an I/O error while reading /.../org.swift.swiftpm/configuration/mirrors.json

### ISSUE THREAD

**Issue by qbarev** [yonaskolb/Mint#235]
I can't install any dependency via mint. I guess this happens due swift 5.6 and Command Line Tools 13.3

<img width="824" alt="image" src="https://user-images.githubusercontent.com/48885426/160790346-b8edcabb-c2f6-4104-b162-61d9cd8e759c.png">

**Comment by yonaskolb** [comment]
Running `mint install --verbose MakeAWishFoundation/SwiftyMocky` completed successfully for me on my machine using Swift 5.6
```
swift --version
swift-driver version: 1.45.2 Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
Target: x86_64-apple-macosx12.0
```

**Comment by yonaskolb** [comment]
If you checkout that repo locally and run `swift build` does it work?

**Comment by yonaskolb** [comment]
If `swift build` isn't working either it's an issue with your machines configuration or the package, and not related to mint itself

**Comment by qbarev** [comment]
Yes. Reinstalling of Xcode helps
