### ISSUE TITLE
Add Shell Completion Scripts

### ISSUE THREAD

**Issue by tomassliz** [yonaskolb/Mint#239]
It would be great to provide shell completion scripts which allow you to press the tab key on your keyboard to autocomplete commands and arguments when typing a mint command.

One approach how to achieving this is to generate them. Installation instructions for different shells (bash, zsh, fish) and the underlying implementation is available in the [swift-argument-parser repo](https://github.com/apple/swift-argument-parser/blob/main/Sources/ArgumentParser/Documentation.docc/Articles/InstallingCompletionScripts.md).

**Comment by yonaskolb** [comment]
I think moving over to swift argument parser is probably a good idea, which also makes this easier, in terms of implementation and documentation.
