### ISSUE TITLE
i can't install mint

### ISSUE THREAD

**Issue by Sadow32** [yonaskolb/Mint#254]
![image](https://user-images.githubusercontent.com/15316819/206688575-641aea30-0978-4f36-8d1d-ea35e58a4f79.png)

please help me

**Comment by yonaskolb** [comment]
What version of swift are you running
```
swift --version
```

**Comment by Sadow32** [comment]
> What version of swift are you running
> 
> ```
> swift --version
> ```

![image](https://user-images.githubusercontent.com/15316819/206822705-c1af7549-bf77-4e86-ae06-c8ad3de3ce63.png)

**Comment by Sadow32** [comment]
I'm M1 Mac, and run terminal with Rosetta

**Comment by kylebrowning** [comment]
have you tried `brew install mint`?

**Comment by Sadow32** [comment]
> have you tried `brew install mint`?

yes, i have tried it

But now that I've turned off Rosetta and reinstalled Homebrew and the rest of the SDKS, when I tried to install Mint with Homebrew, the bug disappeared, and I'm not sure why for a while.

Thank you, you can turn this off!
