### ISSUE TITLE
Mint doesn't install dependencies

### ISSUE THREAD

**Issue by dmitrySachkov** [yonaskolb/Mint#268]
i am trying to install https://github.com/t-ae/swim and https://github.com/apple/swift-collections using mint but getting error

`brew ls --versions xcodegen || brew install xcodegen
xcodegen 2.33.0
brew ls --versions mint || brew install mint
mint 0.17.5
mint install swiftyfinch/rugby
🌱 Finding latest version of rugby
🌱 rugby 2.0.2 already installed
🌱 Linked rugby 2.0.2 to /Users/dmitrysachkov/.mint/bin
mint install "https://github.com/t-ae/swim"
🌱 Finding latest version of swim
🌱 Cloning swim 3.9.0
🌱 Resolving package
🌱  Executable product not found in swim 3.9.0
make: *** [init] Error 1`

`brew ls --versions xcodegen || brew install xcodegen
xcodegen 2.33.0
brew ls --versions mint || brew install mint
mint 0.17.5
brew upgrade mint
Warning: mint 0.17.5 already installed
mint install swiftyfinch/rugby
🌱 Finding latest version of rugby
🌱 rugby 2.0.2 already installed
🌱 Linked rugby 2.0.2 to /Users/dmitrysachkov/.mint/bin
mint install apple/swift-collections --force
🌱 Finding latest version of swift-collections
🌱 Cloning swift-collections 1.0.4
🌱 Resolving package
🌱  Executable product not found in swift-collections 1.0.4
make: *** [init] Error 1`

what could be the problem?
mint install swiftyfinch/rugby - works

**Comment by yonaskolb** [comment]
Mint can only install executable products, and Swim has none
```
products: [
        // Products define the executables and libraries produced by a package, and make them visible to other packages.
        .library(
            name: "Swim",
            targets: ["Swim"]),
    ],
```
