### ISSUE TITLE
Having an issue while installing mint on Mac M2 Pro

### ISSUE THREAD

**Issue by dbhavya** [yonaskolb/Mint#271]
Hey Yonas, 

Hope you are doing well. I am a test engineer from Hireup. 
Getting in touch with you regarding an issue that we're having when setting up the project with mint.

Mint cannot install packages onto Mac M2 Pro. We are seeing below error message. 
```
Error: The folder “packages” doesn’t exist.
make: *** [packages] Error 1
```

The mint installation seems to be successful. However, we see above error with `./mint bootstrap`

Mint version: 0.17.0
OS version: Currently on Sonoma but the issue existed on Ventura too. 
Hidden `.mint` in the root folder doesn't get created

Neda & Karo says `Hi 👋 `

Please let us know if you need more info. 

Thanks,
Bhavya

**Comment by yonaskolb** [comment]
Hi @dbhavya!

Is this issue still happening? It sounds like perhaps a permissions issue on the machine. The default package installation path (customisable via `MINT_PATH`) is `~/.mint`. Is that directory not getting created? Does just running `mkdir ~/.mint` succeed?
Otherwise try updating to Mint 0.17.5

**Comment by dbhavya** [comment]
Hello @yonaskolb, I did run `mkdir ~/.mint` successfully, and then ran `make`. However, I'm still encountering the same error, even after updating the Mint version to 0.17.5.

**Comment by yonaskolb** [comment]
@dbhavya I'm not sure why mint isn't able to make the path within  `~/.mint` other than some permissions issue. Does running `sudo ./mint bootstrap` work?

**Comment by dbhavya** [comment]
> Reference

@yonaskolb I see the same error with `sudo ./mint bootstrap` too.

````
🌱 Finding latest version of Sourcery@2.1.2
Error: The folder “packages” doesn’t exist.
````
