### ISSUE TITLE
Can `mint run` be used without an internet connection?

### ISSUE THREAD

**Issue by colejd** [yonaskolb/Mint#273]
Hello!

When I run `mint run _` without an internet connection, it fails. For example:

```
➜ mint run swiftgen
🌱 Finding latest version of SwiftGen
🌱  Git repo not found at "https://github.com/SwiftGen/SwiftGen.git"
```

Is this desired behavior? SwiftGen is already installed, and I don't want `mint run` to update my dependencies without asking me first. I imagine that's what the `--no-install` option is for, but it still doesn't bypass the network check:

```
➜ mint run --no-install swiftgen
🌱 Finding latest version of SwiftGen
🌱  Git repo not found at "https://github.com/SwiftGen/SwiftGen.git"
```

What should I do?

**Comment by yonaskolb** [comment]
Hi @colejd.
If no version is specified, mint fetches the newest version from the remote repo. You can specify a version with  `mint run swiftgen@6.6.2` or by adding the package and version to a Mintfile

**Comment by colejd** [comment]
Gotcha, thanks!
