### ISSUE TITLE
Solve Swift 4 Charactors deprecated Issue

### ISSUE THREAD

**Issue by satishbabariya2** [yonaskolb/Mint#34]
Characters deprecated in Swift4 so cant able to build Project.

**Comment by yonaskolb** [comment]
Hi @satishbabariya2. The deprecation warning are from some of Mint's dependencies. But they are just warnings, not errors, so you should still be able to build

**Comment by yonaskolb** [comment]
Closing this for now. Let me know if you have any problems @satishbabariya2
