### ISSUE TITLE
Make folder to mint configurable

### ISSUE THREAD

**Issue by Lutzifer** [yonaskolb/Mint#46]
It would be great to have an environment variable to define, where the mint packages are stored (defaulting to "/usr/local/lib/mint/packages/").

This way, one could cache them easier in certain environments (e.g. build servers).

**Comment by yonaskolb** [comment]
Yeah great suggestion 👍

**Comment by yonaskolb** [comment]
PR's welcome! 😉

**Comment by Lutzifer** [comment]
this could be a good addition to get the access problems faced when running the brew tests (#54) solved.

**Comment by yonaskolb** [comment]
Yes, this would be good. The path is already configurable in code, so it wouldn't be that hard to modify it with a `MINT_PATH` ENV

**Comment by Lutzifer** [comment]
Will take another attempt on this, as I will have to refactor a bit to get the additional arguments at the correct time, as currently the mint object is initialised before any arguments are parsed.

**Comment by yonaskolb** [comment]
@Lutzifer current master has made `Mint` a class, so it can be mutated after it's created. I did this for the `--silent` argument to easily swap out `mint.standardOutput`. This should make it easier to simply change `mint.path`

**Comment by yonaskolb** [comment]
Done here #65

**Comment by Lutzifer** [comment]
@yonaskolb 
ah, just saw your changes after beginning the above implementation
