### ISSUE TITLE
Use the package's stdout with the run command

### ISSUE THREAD

**Issue by yutailang0119** [yonaskolb/Mint#57]
If samplepackage print standard output and inserts this into a file, I would execute this with run command.

```shell
$ mint run sample/samplepackage@master samplecommand > Sample.swift
```

However, Mint output is also inserted in file.

```swift
struct Sample {
    ...
}
🌱  simplepackage already installed
🌱  Running simplepackage master...
```

Are there any effective idea?

#### Example 

- [ishkawa/DIKit](https://github.com/ishkawa/DIKit)

**Comment by toshi0383** [comment]
I would do `--silent` by default, if the command is already installed.

**Comment by yutailang0119** [comment]
Thanks for idea! 
I try implement!
