### ISSUE TITLE
Error when I try to install mint with brew

### ISSUE THREAD

**Issue by amine2233** [yonaskolb/Mint#8]
Hello,

When I try to install mint via brew, I have this error

swift build --disable-sandbox -c release -Xswiftc -static-stdlib
error: failed to clone; Cloning into bare repository '/private/tmp/mint-20171003-62946-56b4dl/Mint-0.4.0/.build/repositories/PathKit.git--1865447967743163058'...
fatal: unable to access 'https://github.com/kylef/PathKit.git/': Could not resolve host: github.com
error: product dependency 'ShellOut' not found
error: product dependency 'Rainbow' not found
error: product dependency 'PathKit' not found
error: product dependency 'Rainbow' not found
error: product dependency 'Guaka' not found
Fetching https://github.com/kylef/PathKit.git
Fetching https://github.com/JohnSundell/ShellOut.git
Fetching https://github.com/onevcat/Rainbow.git
Fetching https://github.com/nsomar/Guaka.git
Fetching https://github.com/kylef/Spectre.git
Fetching https://github.com/oarrabi/StringScanner
make: *** [build] Error 1

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
yonaskolb/mint

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:226:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:184:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:284:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:231:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:244:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:369:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:365:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:419:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:133:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:26:in `<main>'

**Comment by yonaskolb** [comment]
Hi @amine2233 
That's a very weird error, it almost looks like there was a connection issue with github while you were installing. Could you maybe just try again, and see if it works?

**Comment by amine2233** [comment]
I have the same error in two different Mac

**Comment by yonaskolb** [comment]
Interesting, I can't say I've seen that before, and it's installing fine for for myself and others. Not sure what the issue is.
What version of homebrew do you have?
```
brew --version
```

**Comment by amine2233** [comment]
Homebrew 1.3.4
Homebrew/homebrew-core (git revision a53a8; last commit 2017-10-03)

**Comment by amine2233** [comment]
I use Xcode 9

**Comment by yonaskolb** [comment]
Yeah, that's the same version of homebrew I have.
And Xcode 9 is the default version of xcode on the machine?
```
xcode-select -p
```
Otherwise I have no idea, sorry. You can try installing via make as well and see if that works?
```sh
$ git clone https://github.com/yonaskolb/mint.git
$ cd mint
$ make
```

**Comment by amine2233** [comment]
it's work, when I clone the mint project but it found an error, I sent the error above,

```/Applications/Xcode.app/Contents/Developer```

**Comment by yonaskolb** [comment]
Glad you got it working. Yeah those are warnings from dependencies that haven't updated to Swift 4 yet.
If you figure out the homebrew issue let me know.

Any thoughts @orta?

**Comment by amine2233** [comment]
thinks for your helping
