### ISSUE TITLE
Please suggest how to build a network tool using private keys

### ISSUE THREAD

**Issue by shpakovski** [yonaskolb/Mint#81]
Hello, Mint is amazing!
This is not an issue but more like asking for idea or help 😇

I’m working on a command line utility for reading data from Google services. One of its supported commands is `auth`, and it’s needed to save credentials for the future access locally. However, such command requires special API keys for OAuth(2) generated by the API provider. What is the best way, if any, to “borrow” my secret tokens for building a tool during `mint install` on the client machine?

Thanks in advance!

**Comment by yonaskolb** [comment]
Hi @shpakovski, glad you like it!

I'm not sure I 100% understand your question, but you would like to use some api keys in your swift command line tool right? I don't know if accessing them during `mint install` is the best place, but rather in your executable itself when it runs.
There are various ways of accessing these in your command line tool, for example:
- passing by an argument (must be done everytime)
- an environment variable (can be setup within someones toolchain)
- have some file at a standard path that it reads from
- some way of saving and loading it within the tool, to local storage or preferably the keychain. Your command could ask for it interactively if it doesn't have the key yet, or require them to pass it in the first time.

Hope that helps, sorry if I've misunderstood your question.

**Comment by shpakovski** [comment]
Yes, there is a bit of misunderstanding, sorry 😅

The thing is that I don’t want all customers of the CLI to generate their own API Keys in order to use the app. My command-line tool is similar to any mobile client: it runs the OAuth login page with a custom identifier and secret string to acquire the access token per device!

So those keys must be in the binary but not in the codebase 🙇‍♂️ Thanks again!

**Comment by yonaskolb** [comment]
Ah I see. Without creating your own simple server that validates encrypted keys and forwards calls to Google, I'm not sure how you can make this completely secure.

You could compile the key into the binary somehow but only if building manually, and it couldn't be built by mint. Even then someone clever could probably extract the key out of your binary if they wanted to, but that is probably hard enough that no-one would bother 😄

I'm not a security expert though so there might be another way to do what you're after

**Comment by shpakovski** [comment]
Right, the secret string should be in the binary but not in the codebase 🙌

> Without creating your own simple server that validates encrypted keys and forwards calls to Google.

This is a way to go, thanks a lot! I will just modify this approach a bit 👏

**Comment by shpakovski** [comment]
Follow-up, if you’re curious: https://stackoverflow.com/questions/1983990/how-to-open-source-an-application-that-uses-api-keys I.e. such command-line tools should be distributed as binaries, so `mint` is not suitable for such cases. I will use it next time though, thanks again! 😄
