### ISSUE TITLE
Add "-p" option to bootstrap

### ISSUE THREAD

**Issue by Lutzifer** [yonaskolb/Mint#83]
It should be possible to skip linking when running bootstrap.

This way, "mint bootstrap" can be used to install all versions specified in the Mintfile for later use without linking them.

**Comment by yonaskolb** [comment]
That's what happens by default. Are you seeing different behaviour?

**Comment by Lutzifer** [comment]
Ah, ok, than we should perhaps just clarify it in the readme:

install: Installs a package, so it can be run with run later, and also links that version globally
bootstrap: Installs all the packages in your Mintfile

This led me to assume it did link them all.

**Comment by yonaskolb** [comment]
Fixed
