### ISSUE TITLE
Forward stderr from subcommands

### ISSUE THREAD

**Issue by mklbtz** [yonaskolb/Mint#86]
- Using [swiftenv](https://github.com/kylef/swiftenv) to manage Swift versions
- Using Mint v0.10.2

When running `mint install jakeheis/Ice --verbose`, I received this error:
```
...
🌱  Building Ice with SPM...
no such command: swift
```
I realized this was because Ice required Swift version 4.1, which I did not have installed. 

The output `no such command: swift` comes from swiftenv shims via `stdout`. It also warns you via `stderr` when the required version is not installed, e.g. `swiftenv: version '4.1' (set by .swift-version) is not installed`.

Mint seems to forward `stdout` in verbose mode, but I didn't see the `stderr` output from swiftenv. This would be pretty helpful for debugging package build errors.

**Comment by yonaskolb** [comment]
This is fixed in #116

**Comment by yonaskolb** [comment]
Fixed in 0.11.3
