### ISSUE TITLE
Package upgrading routine is currently unintuitive

### ISSUE THREAD

**Issue by dreymonde** [yonaskolb/Mint#87]
Mint is just awesome, but I think that the package update part can be improved. In particular:

1) There is no command (or I don’t know one) that can update all outdated packages (just `mint update` would be nice).
2) When you type `mint update`, you need to provide full package name (for example, `mint update jakeheis/Ice`), but `mint list` shows the name without the author name (so just `Ice` in this example).

My proposal is also to rename `mint update` to more Homebrew-like `mint upgrade`, but that’s totally up to you. I can try to resolve first two mentioned issues and submit a PR if you’re okay with that. Just let me know!

**Comment by dreymonde** [comment]
@yonaskolb any thoughts on this? 🙂

**Comment by yonaskolb** [comment]
Sounds good. Feel free to open some PR’s. 

In terms of the name, neither update or upgrade really communicates what it does. To do a normal update you can just run `install` without a version and if there’s a newer version it will install that. The current update is just sort of a re-install. I was even thinking of removing it and have a `—force` or `—reinstall` flag to force a new build. 
Maybe it could then be repurposed into an update all as you suggest

**Comment by yonaskolb** [comment]
`update` replaced with `install --force` in #96

**Comment by yonaskolb** [comment]
`mint install` now supports specifying just the package name in #100
