### ISSUE TITLE
Add support for specifying branch name 

### ISSUE THREAD

**Issue by ryohey** [yonaskolb/Mint#9]
> version (optional): The git version of the packge. It is usually a tag but can also be a branch. If this is left out the version will default to the latest tag, or if there are no tags then master.

Document says third option string can be branch name.
Haven't you implemented it? It seems to supported only master branch.

https://github.com/yonaskolb/Mint/blob/10d99f9d8422d1ad78e3db5891756fb9a53facb1/Sources/Mint/main.swift#L61

I want to implement to support reading branch name other than master.
But I think that the syntax cannot make distinction between command and version in some circumstances.
`mint run yonaskolb/xcodegen xcodegen`
This can be interpreted as `user/repo branch` or `user/repo command`.

Although this does not maintain backward compatibility, I suggest the syntax like `user/repo@branch command`.

**Comment by yonaskolb** [comment]
Hi @ryohey, any branch is supported. That code you point to is just trying to guess what the second parameter is if you only specify 2. 
so you can use something like `mint run yonaskolb/xcodegen mybranch xcodegen`

Having them be flags would be less ambiguous but more verbose. I like your @ suggestion, though as you say it would be a breaking change

**Comment by ryohey** [comment]
Thanks I understood that this is expected behavior.

**Comment by yonaskolb** [comment]
@ryohey, the @ behaviour has been added in #11

**Comment by ryohey** [comment]
Ohhhh YES!!
