### ISSUE TITLE
Run fails with "Unknown command: `swiftgen`" on 0.11.0

### ISSUE THREAD

**Issue by simonseyer** [yonaskolb/Mint#98]
**Mintfile:**
```
swiftgen/swiftgen@master
realm/swiftlint@0.26.0
```

**Command:**
`mint run -m "../Mintfile" swiftgen/swiftgen swiftgen config run --config COBI/swiftgen.yml`

This worked with Mint `0.10.2`. Also `mint run -m "../../Mintfile" swiftgen/swiftgen` works (by switching to the subfolder where the config for swiftgen is located and omitting the argument). `mint run -m "../Mintfile" swiftgen/swiftgen --config COBI/swiftgen.yml` on the other hand says `Couldn't find executable "--config"`.

**Comment by yonaskolb** [comment]
Thanks for raising this @simonseyer! It was a regression that slipped through. Fixed in 0.11.1

**Comment by simonseyer** [comment]
Cool :+1: looking forward to it getting published on homebrew

**Comment by yonaskolb** [comment]
It's in review 👍 https://github.com/Homebrew/homebrew-core/pull/30921

**Comment by yonaskolb** [comment]
Homebrew update merged
